export 'package:componentes_prog3/screens/inputs_screen.dart';
export 'package:componentes_prog3/screens/alert_screen.dart';
export 'package:componentes_prog3/screens/avatar_screen.dart';
export 'package:componentes_prog3/screens/card_screen.dart';
export 'package:componentes_prog3/screens/container_screen.dart';
export 'package:componentes_prog3/screens/dependencies_screen.dart';
export 'package:componentes_prog3/screens/home_screen.dart';
export 'package:componentes_prog3/screens/listview_screen.dart';
export 'package:componentes_prog3/screens/slider_screen.dart';